# action.yml
name: SQLite schema lint
description: Enforce constraints on SQLite schemas
inputs:
  schema-file:
    description: SQL schema file to lint
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.schema-file }}
